
// This file is generated. Do not edit! 
// Edit the cards.csv instead and regenerate

use array::ArrayTrait;
use option::OptionTrait;
fn get(card_id: u32) -> Option<felt252> {
    let a = array![
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave'),
        Option::Some('cave_familiar'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest'),
        Option::Some('forest_familiar'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow'),
        Option::Some('meadow_familiar'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano'),
        Option::Some('volcano_familiar'),

    ];
    a.get(card_id)
}
