
// This file is generated. Do not edit! 
// Edit the cards.csv instead and regenerate

use array::ArrayTrait;
use option::OptionTrait;
fn get(card_id: u32) -> Option<felt252> {
    let a = array![
        option::Some(1),
        option::Some(2),
        option::Some(3),
        option::Some(4),
        option::Some(5),
        option::Some(6),
        option::Some(7),
        option::Some(8),
        option::Some(9),
        option::Some(10),
        option::Some(11),
        option::Some(12),
        option::Some(13),
        option::Some(14),
        option::Some(15),
        option::Some(16),
        option::Some(17),
        option::Some(18),
        option::Some(19),
        option::Some(20),
        option::Some(21),
        option::Some(22),
        option::Some(23),
        option::Some(24),
        option::Some(25),
        option::Some(26),
        option::Some(27),
        option::Some(28),
        option::Some(29),
        option::Some(30),
        option::Some(31),
        option::Some(32),
        option::Some(33),
        option::Some(34),
        option::Some(35),
        option::Some(36),
        option::Some(37),
        option::Some(38),
        option::Some(39),
        option::Some(40),
        option::Some(41),
        option::Some(42),
        option::Some(43),
        option::Some(44),
        option::Some(45),
        option::Some(46),
        option::Some(47),
        option::Some(48),
        option::Some(49),
        option::Some(50),
        option::Some(51),
        option::Some(52),
        option::Some(53),
        option::Some(54),
        option::Some(55),
        option::Some(56),
        option::Some(57),
        option::Some(58),
        option::Some(59),
        option::Some(60),
        option::Some(61),
        option::Some(62),
        option::Some(63),
        option::Some(64),
        option::Some(65),
        option::Some(66),
        option::Some(67),
        option::Some(68),
        option::Some(69),
        option::Some(70),
        option::Some(71),
        option::Some(72),
        option::Some(73),
        option::Some(74),
        option::Some(75),
        option::Some(76),
        option::Some(77),
        option::Some(78),
        option::Some(79),
        option::Some(80),
        option::Some(81),
        option::Some(82),
        option::Some(83),
        option::Some(84),
        option::Some(85),

    ];
    a.get(card_id)
}
