use option::OptionTrait;
// This will be autogenerated from spreadsheet columns
// unfortunately are there are no static maps in Cairo we need to implement that 
// as an if statement
fn get(card_id: u128) -> bool {
    if card_id == 0 {
        true
    } else {
        false
    }
}
