
// This file is generated. Do not edit! 
// Edit the cards.csv instead and regenerate

use array::ArrayTrait;
use option::OptionTrait;
fn get(card_id: u32) -> Option<felt252> {
    let a = array![
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('FALSE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('FALSE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('FALSE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('TRUE'),
        Option::Some('FALSE'),
        Option::Some('FALSE'),

    ];
    a.get(card_id)
}
