
// This file is generated. Do not edit! 
// Edit the cards.csv instead and regenerate

use array::ArrayTrait;
use option::OptionTrait;
fn get(card_id: u32) -> Option<felt252> {
    let a = array![
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),
        option::Some(1),

    ];
    a.get(card_id)
}
