
// This file is generated. Do not edit! 
// Edit the cards.csv instead and regenerate

use array::ArrayTrait;
use option::OptionTrait;
fn get(card_id: u32) -> Option<felt252> {
    let a = array![
        Option::Some(3),
        Option::Some(1),
        Option::Some(-1),
        Option::Some(1),
        Option::Some(3),
        Option::Some(2),
        Option::Some(1),
        Option::Some(1),
        Option::None,
        Option::Some(3),
        Option::Some(4),
        Option::None,
        Option::Some(-1),
        Option::Some(1),
        Option::Some(3),
        Option::Some(-1),
        Option::Some(2),
        Option::Some(2),
        Option::None,
        Option::Some(2),
        Option::None,
        Option::Some(2),
        Option::Some(3),
        Option::None,
        Option::Some(-1),
        Option::None,
        Option::None,
        Option::Some(2),
        Option::Some(1),
        Option::None,
        Option::Some(2),
        Option::Some(1),
        Option::None,
        Option::Some(1),
        Option::Some(1),
        Option::Some(2),
        Option::Some(3),
        Option::None,
        Option::Some(1),
        Option::Some(1),
        Option::Some(3),
        Option::None,
        Option::Some(2),
        Option::Some(1),
        Option::None,
        Option::Some(1),
        Option::None,
        Option::Some(2),
        Option::None,
        Option::Some(1),
        Option::Some(1),
        Option::Some(2),
        Option::None,
        Option::Some(3),
        Option::Some(5),
        Option::Some(1),
        Option::Some(1),
        Option::Some(1),
        Option::Some(2),
        Option::Some(1),
        Option::None,
        Option::None,
        Option::None,
        Option::None,
        Option::Some(3),
        Option::None,
        Option::Some(2),
        Option::Some(6),
        Option::None,
        Option::None,
        Option::Some(1),
        Option::Some(1),
        Option::Some(2),
        Option::None,
        Option::Some(5),
        Option::None,
        Option::None,
        Option::Some(1),
        Option::Some(1),
        Option::Some(2),
        Option::Some(4),
        Option::Some(3),
        Option::Some(1),
        Option::None,
        Option::None,

    ];
    a.get(card_id)
}
