/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ValueInGame: (() => {
      const name = "ValueInGame";
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Owner: (() => {
      const name = "Owner";
      return defineComponent(
        world,
        {
          address: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
