/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Familiar: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.BigInt, game_id: RecsType.BigInt, familiar_type_id: RecsType.BigInt },
        {
          metadata: {
            name: "Familiar",
            types: ["u128", "u128", "u128"],
            customTypes: [],
          },
        }
      );
    })(),
    Occupied: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.BigInt, until: RecsType.Number, doing: RecsType.Number, reaped: RecsType.Boolean },
        {
          metadata: {
            name: "Occupied",
            types: ["u128", "u32", "enum", "bool"],
            customTypes: ["Action"],
          },
        }
      );
    })(),
    Owner: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.BigInt, address: RecsType.BigInt },
        {
          metadata: {
            name: "Owner",
            types: ["u128", "contractaddress"],
            customTypes: [],
          },
        }
      );
    })(),
    Valueingame: (() => {
      return defineComponent(
        world,
        { entity_id: RecsType.BigInt, game_id: RecsType.BigInt, value: RecsType.Number },
        {
          metadata: {
            name: "Valueingame",
            types: ["u128", "u128", "u32"],
            customTypes: [],
          },
        }
      );
    })(),
  };
}
