name: my-workflow

on:
    push:
    pull_request:

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./client

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
