name: Contracts

on:
  push:
  pull_request:

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
    - uses: actions/checkout@v3
    - run: curl -L https://install.dojoengine.org | bash
    - run: /home/runner/.config/.dojo/bin/dojoup
    - run: |
        /home/runner/.config/.dojo/bin/sozo build
        /home/runner/.config/.dojo/bin/sozo test